# RHEL-certified ko base: ubi-micro plus OpenShift preflight /licenses requirement.
# Built multi-arch and pushed before `ko build` in publish-modules-rhel.
FROM odigosdemo.jfrog.io/docker/ubi9/ubi-micro:latest
COPY licenses /licenses
COPY LICENSE /licenses/.
